services:
    mariadb:
        build:
           context: srcs/mariadb
           dockerfile: Dockerfile
        image: mariadb
        container_name: mariadb
        restart: always
        environment:
             - MYSQL_ROOT_PASSWORD=mypassword
             - MYSQL_DATADIR=/var/lib/mysql
        networks:
            - wp
    wordpress:
        build:
           context: srcs/wordpress
           dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        restart: always
        volumes:
               - wordpress:/var/www/html/
        networks:
               - wp
        depends_on:
               - mariadb
    ngnix:
        build:
           context: srcs/ngnix
           dockerfile: Dockerfile
        image: ngnix
        container_name: ngnix
        ports: 
               - "80:80"
        volumes:
               - wordpress:/var/www/html/
        restart: always
        networks:
               - wp
networks:
    wp:
        driver: bridge

volumes:
       wordpress:
               