services:
    wordpress:
        build:
           context: srcs/wordpress
           dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        restart: always
       #  volumes:
       #         - wordpress:/var/www/html/
        networks:
               - wp
    ngnix:
        build:
           context: srcs/ngnix
           dockerfile: Dockerfile
        image: ngnix
        container_name: ngnix
        ports: 
               - "80:80"
        depends_on: 
               - wordpress
        restart: always
        networks:
               - wp
networks:
    wp:
        driver: bridge

volumes:
    nginx:
#     wordpress:
               