services:
    mariadb:
        build:
           context: srcs/mariadb
           dockerfile: Dockerfile
        image: mariadb
        container_name: mariadb
        restart: always
        ports:
             - "3306-3306"
        environment:
             - MYSQL_ROOT_PASSWORD=mypassword
             - MYSQL_DATADIR=/var/lib/mysql
    wordpress:
        build:
           context: srcs/wordpress
           dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        restart: always
        depends_on:
               - mariadb
       #  volumes:
       #         - wordpress:/var/www/html/
        networks:
               - wp
    ngnix:
        build:
           context: srcs/ngnix
           dockerfile: Dockerfile
        image: ngnix
        container_name: ngnix
        ports: 
               - "80:80"
        depends_on: 
               - wordpress
        restart: always
        networks:
               - wp
networks:
    wp:
        driver: bridge

volumes:
    nginx:
#     wordpress:
               