services:
    wordpress:
        build:
           context: srcs/wordpress
           dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        restart: always
        volumes:
               - wordpress:/var/www/html/
        networks:
               - wp
    ngnix:
        build:
           context: srcs/ngnix
           dockerfile: Dockerfile
        image: ngnix
        container_name: ngnix
        ports: 
               - "443:443"
        depends_on: 
               - wordpress
        restart: always
        volumes:
               - nginx:/etc/nginx/conf.d
        networks:
               - wp
networks:
    wp:
        driver: bridge

volumes:
    nginx:
    wordpress:
               