version: '3'
services:
     mariadb:
        build:
           context: srcs/mariadb
           dockerfile: Dockerfile
        image: mariadb
        container_name: mariadb
        restart: always
        environment:
             - MYSQL_ROOT_PASSWORD=mypassword
             - MYSQL_DATADIR=/var/lib/mysql
        networks:
             - wp
        volumes:
             - MDB:/var/lib/mysql
     wordpress:
        build:
           context: srcs/wordpress
           dockerfile: Dockerfile
        image: wordpress
        container_name: wordpress
        restart: always
        volumes:
               - wordpress:/var/www/html/wp
        networks:
               - wp
        depends_on:
               - mariadb
     ngnix:
        build:
           context: srcs/ngnix
           dockerfile: Dockerfile
        image: ngnix
        container_name: ngnix
        ports: 
               - "443:443"
        volumes:
               - wordpress:/var/www/html/wp
        restart: always
        networks:
               - wp
networks:
    wp:
        driver: bridge

volumes:
       wordpress:
              driver_opts:
                     type: none
                     device: /home/aaqari/data/wordpress/wp
                     o: bind
       MDB:
              driver_opts:
                     type: none
                     device: /home/aaqari/data/db
                     o: bind