services:
    wordpress:
        build: /srcs/wordpress/
        image: wordpress
    ngnix:
        build: /srcs/ngnix
        image: ngnix
        ports: 
               - 443-443
        depends_on: 
               - wordpress