FROM debian:buster

#insall Wordpress
RUN apt-get update
RUN apt-get install -y zip
RUN apt-get install -y unzip
RUN apt-get install -y curl

#Download wordpress files
# RUN curl -LO https://wordpress.org/latest.zip
# RUN unzip latest.zip